services:
  app:
    image: harshau04/interview.ai:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI="mongodb://mongodb:27017/interview-ai"
      - GEMINI_API_KEY="${GEMINI_API_KEY}"
      - ELEVENLABS_API_KEY="${ELEVENLABS_API_KEY}"
    restart: unless-stopped
